# Heatmap: Fuel prices across cities over time (using pivot table)
pivot_data = data.pivot_table(values='rate', index='date', columns='city')
plt.figure(figsize=(12, 6))
sns.heatmap(pivot_data, cmap='coolwarm', cbar_kws={'label': 'Fuel Price (INR)'})
plt.title('Heatmap of Fuel Prices Across Cities Over Time')
plt.xlabel('City')
plt.ylabel('Date')
plt.tight_layout()
plt.show()
